name         'overholw-cassandra'
version      '0.4.0'
author       'Jochen Schalanda,Warren Overholt'
license      'Apache 2.0'
project_page 'https://github.com/overholw/puppet-cassandra'
source       'https://github.com/overholw/puppet-cassandra'
summary      'Puppet module to install Apache Cassandra from the DataStax distribution'
description  'A Puppet module to install the DataStax Community edition using the official repositories.'
dependency   'puppetlabs/stdlib', '>= 3.0.0'
dependency   'puppetlabs/apt', '1.x'
